[serve]
address = "127.0.0.1"
port = 8000
# Open a browser tab once the initial build is complete.
open = false
# Disable auto-reload of the web app.
no_autoreload = true

[tools]
tailwindcss = "3.3.3"
