[package]
name = "graph"
version = "0.1.3"
authors = ["azzamsa <vcs@azzamsa.com>"]
categories = ["web-programming"]
edition = "2021"
exclude = ["/README.md"]
keywords = ["boilerplate"]
license = "MIT"
repository = "https://github.com/azzamsa/rust-graphql"
description = "Rust GraphQL Template"

[dependencies]
axum = "0.5.13"
hyper = "0.14.20"
tokio = { version = "1.20.0", features = ["macros", "rt-multi-thread"] }

# GraphQL
async-graphql = { version = "4.0.5", features = ["uuid", "chrono"] }
async-graphql-axum = "4.0.5"

# Rest
utoipa = { version = "2.0.0", features = ["axum_extras"] }
utoipa-swagger-ui = { version = "2.0.0", features = ["axum"] }

# Database
sqlx = { version = "0.6.0", features = ["runtime-async-std-native-tls", "postgres", "offline", "uuid", "chrono", "migrate"] }

# log
env_logger = "0.9.0"
log = "0.4"

base64 = "0.13.0"
chrono = { version = "0.4", features = ["serde"] }
dotenv = "0.15"
serde = "1.0"
serde_json = "1.0"
thiserror = "1.0"
time = "0.3"
ulid = { version = "0.6.0", features = ["uuid"] }
url = "2.2"
uuid = "1.1.2"

[dev-dependencies]
# git hooks
cargo-husky = { version = "1", features = ["user-hooks"] }

anyhow = "1.0"
cynic = "1.0.0"
hyper = { version = "0.14.20", features = ["full"] }
mime = "0.3.16"
serde = { version = "1.0", features = ["derive"] }
tower = { version = "0.4", features = ["util"] }

# cross-rs configuration
[package.metadata.cross.target.x86_64-unknown-linux-gnu]
# The latest version of cross-rs doesn't include OpenSSL support
pre-build = [
  "dpkg --add-architecture $CROSS_DEB_ARCH",
  "apt-get update && apt-get install --assume-yes libssl-dev:$CROSS_DEB_ARCH",
]
