// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    'IPh:handWaving': typeof import('~icons/ph/hand-waving')['default']
    'ITabler:language': typeof import('~icons/tabler/language')['default']
    'ITabler:menu2': typeof import('~icons/tabler/menu2')['default']
    'ITabler:moodSad': typeof import('~icons/tabler/mood-sad')['default']
    'ITabler:x': typeof import('~icons/tabler/x')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
