name: ci

on:
  pull_request: null
  push:
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Install dprint
        run: |
          curl --location https://github.com/dprint/dprint/releases/download/0.30.3/dprint-x86_64-unknown-linux-gnu.zip --output dprint.zip
          unzip dprint.zip
          cp dprint ~/.cargo/bin/
          dprint --version

      - name: Install pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 7.6.0

      - name: Install dependencies
        run: |
          pnpm i

      - name: Lint
        run: |
          make check
