name: Leptos SSR (CI)

on:
  push:
    paths:
      -  src/leptos/ssr/**
      - .github/workflows/leptos_ssr.yml
  pull_request:
    paths:
      -  src/leptos/ssr/**
      - .github/workflows/leptos_ssr.yml

defaults:
  run:
    working-directory: src/leptos/ssr

jobs:
  code_quality:
    name: Code quality
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy, rustfmt

      - uses: taiki-e/install-action@just
      - uses: taiki-e/install-action@dprint
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-leptos, rustywind

      - name: Show version information
        shell: bash
        run: |
          rustc --version
          cargo --version
          cargo fmt --version
          rustywind --version
          cargo-leptos --version

      - name: Run check
        run: just check


  min_version:
    name: Minimum supported rust version
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - uses: actions-rust-lang/setup-rust-toolchain@v1

      - uses: taiki-e/install-action@just
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-leptos, rustywind

      - name: Show version information
        shell: bash
        run: |
          rustc --version
          cargo --version
          rustywind --version
          cargo-leptos --version

      - name: Run build
        run:  just build

  build:
    name: ${{ matrix.job.os }} (${{ matrix.job.target }})
    runs-on: ${{ matrix.job.os }}

    strategy:
      fail-fast: false
      matrix:
        job:
          - { os: ubuntu-latest, target: wasm32-unknown-unknown   }

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: ${{ matrix.job.target }}

      - uses: taiki-e/install-action@just
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-leptos, rustywind

      - name: Show version information
        shell: bash
        run: |
          rustc --version
          cargo --version
          rustywind --version
          cargo-leptos --version

      - name: Run build
        run:  just build
