name: Leptos (CI)

env:
  MIN_SUPPORTED_RUST_VERSION: "1.73.0"
  # https://github.com/oxalica/rust-overlay/tree/master/manifests/nightly
  RUST_TOOLCHAIN: "nightly-2023-10-06"

on:
  push:
    paths:
      -  src/leptos/**
      - .github/workflows/leptos.yml
  pull_request:
    paths:
      -  src/leptos/**
      - .github/workflows/leptos.yml

defaults:
  run:
    working-directory: src/leptos

jobs:
  code_quality:
    name: Code quality
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          # https://github.com/oxalica/rust-overlay/tree/master/manifests/nightly
          toolchain: ${{ env.RUST_TOOLCHAIN }}
          components: clippy, rustfmt

      - name: Install JS dependencies
        run: |
          npm install

      - name: Install latest dprint release
        uses: taiki-e/install-action@dprint

      - name: Install latest just release
        uses: taiki-e/install-action@just

      - name: Install latest rustywind release
        uses: taiki-e/install-action@rustywind

      - name: Ensure MSRV is set in `clippy.toml`
        run: grep "^msrv = \"${{ env.MIN_SUPPORTED_RUST_VERSION }}\"\$" clippy.toml

      - name: Run check
        run: just check


  min_version:
    name: Minimum supported rust version
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@nightly

      - name: Install latest just release
        uses: taiki-e/install-action@just

      - name: Install latest just release
        uses: taiki-e/install-action@just

      - name: Install latest rustywind release
        uses: taiki-e/install-action@rustywind

      - name: Run test
        run:  just test

  build:
    name: ${{ matrix.job.os }} (${{ matrix.job.target }})
    runs-on: ${{ matrix.job.os }}

    strategy:
      fail-fast: false
      matrix:
        job:
          - { os: ubuntu-latest, target: wasm32-unknown-unknown   }

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.RUST_TOOLCHAIN }}
          target: ${{ matrix.job.target }}

      - name: Install JS dependencies
        run: |
          npm install

      - name: Install latest trunk release
        uses: taiki-e/install-action@v2
        with:
          tool: trunk

      - name: Install latest just release
        uses: taiki-e/install-action@just

      - name: Install latest rustywind release
        uses: taiki-e/install-action@rustywind

      - name: Show version information
        shell: bash
        run: |
          gcc --version || true
          rustup -V
          rustup toolchain list
          rustup default
          cargo -V
          rustc -V

          rustywind --version

      - name: Run build
        run:  just build

      - name: Run test
        run:  just test
