name: Svelte (CI)

on:
  push:
    paths:
      -  src/svelte/**
      - .github/workflows/svelte.yml
  pull_request:
    paths:
      -  src/svelte/**
      - .github/workflows/svelte.yml

defaults:
  run:
    working-directory: src/svelte

jobs:
  ci:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Install latest dprint release
        uses: taiki-e/install-action@v1
        with:
          tool: dprint

      - name: Install latest just release
        uses: extractions/setup-just@v1

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Install dependencies
        run: |
          pnpm i

      - name: Lint
        run: |
          just check
