name: SvelteKit (CI)

on:
  push:
    paths:
      -  src/sveltekit/**
      - .github/workflows/sveltekit.yml
  pull_request:
    paths:
      -  src/sveltekit/**
      - .github/workflows/sveltekit.yml

defaults:
  run:
    working-directory: src/sveltekit

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7

      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: pnpm
          cache-dependency-path: src/sveltekit/pnpm-lock.yaml

      - name: Install dprint
        run: |
          curl --location https://github.com/dprint/dprint/releases/download/0.30.3/dprint-x86_64-unknown-linux-gnu.zip --output dprint.zip
          unzip dprint.zip
          cp dprint ~/.cargo/bin/
          dprint --version

      - name: Install
        run: pnpm install

      - name: Lint
        run: |
          make lint

  test-e2e:
    name: Test E2E
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache
          key: cypress-cache-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/
          cache: pnpm
          cache-dependency-path: src/sveltekit/pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install

      - name: Install Playwright Browsers
        run: npx playwright@1.25.2 install --with-deps

      - name: Run Playwright tests
        run: pnpm dlx playwright@1.25.2 test

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
